#!/usr/bin/env bash

MON="$(xrandr | rg 'primary' | cut -f1 -d ' ')"    # Discover monitor name with: xrandr | grep " connected"
STEP=5          # Step Up/Down brightnes by: 5 = ".05", 10 = ".10", etc.

# Get Previous Light Value
PREV="$(cat ~/.cache/screen_brightness)"

CurrBright=$( xrandr --verbose --current | grep ^"$MON" -A5 | tail -n1 )
CurrBright="${CurrBright##* }"  # Get brightness level with decimal place

Left=${CurrBright%%"."*}        # Extract left of decimal point
Right=${CurrBright#*"."}        # Extract right of decimal point

MathBright="0"
[[ "$Left" != 0 && "$STEP" -lt 10 ]] && STEP=10     # > 1.0, only .1 works
[[ "$Left" != 0 ]] && MathBright="$Left"00          # 1.0 becomes "100"
[[ "${#Right}" -eq 1 ]] && Right="$Right"0          # 0.5 becomes "50"
MathBright=$(( MathBright + Right ))

[[ "$1" == "Up" || "$1" == "+" ]] && MathBright=$(( MathBright + STEP ))
[[ "$1" == "Down" || "$1" == "-" ]] && MathBright=$(( MathBright - STEP ))
[[ "$1" =~ ^([0-9]+)$ ]] && MathBright="$1"

[[ "${MathBright:0:1}" == "-" ]] && MathBright=0    # Negative not allowed
[[ "$MathBright" -gt 100  ]] && MathBright=100      # Can't go over 1.0
[[ "$MathBright" -lt 50 ]] && MathBright=50         # Can't go under .5

if [[ "${#MathBright}" -eq 3 ]] ; then
    MathBright="$MathBright"000         # Pad with lots of zeros
    CurrBright="${MathBright:0:1}.${MathBright:1:2}"
else
    MathBright="$MathBright"000         # Pad with lots of zeros
    CurrBright=".${MathBright:0:2}"
fi

# Change brightness
xrandr --output "$MON" --brightness "$CurrBright"   # Set new brightness

# Store current brightness into ~/.cache to reuse in i3 startup
printf "$CurrBright" > ~/.cache/screen_brightness

# Display current brightness
# printf "Monitor $MON "
dunstify -r 192519  --icon=~/.config/i3/ico/img_b.jpg "$MON Display Brightness" "$( xrandr --verbose --current | grep ^"$MON" -A5 | tail -n1 | xargs)"
